name = "imc_formalizations"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["ImcFormalizations"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.style.multiGoal = true
weak.linter.style.cdot = true
weak.linter.tacticAnalysis.tryAtEachStepFromEnv = true

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.32.0"

[[lean_lib]]
name = "ImcFormalizations"

[[lean_lib]]
name = "ProblemExtraction"